import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import spectrogram
from sionna.radar.source import RadarSource
import logging

class SpectrogramPlotter:
    """
    Class for generating and plotting the spectrogram of a radar signal.

    Example usage:
    ----------------
    fmcw_source = FMCWSource(...)
    plotter = SpectrogramPlotter(fmcw_source)
    plotter.generate_signal()
    plotter.plot_spectrogram(time_scale=3.0, signal_component='magnitude', save_path='spectrogram.png')
    """

    def __init__(self, radar_source, nperseg=256, noverlap=128, nfft=256, window='hann', cmap='viridis'):
        """
        Initializes the SpectrogramPlotter.

        Parameters:
        -----------
        radar_source : RadarSource or FMCWSource
            Instance of a class derived from RadarSource that generates the signal.
        nperseg : int
            Number of samples per segment for STFT calculation.
        noverlap : int
            Overlap between segments in STFT.
        nfft : int
            FFT size for each segment.
        window : str
            Type of window (e.g., 'hann', 'hamming', etc.).
        cmap : str
            Color map for the spectrogram.
        """
        # Validation of radar_source
        if not isinstance(radar_source, RadarSource):
            raise ValueError("radar_source must be an instance of RadarSource or a derived class.")

        # Validation of spectrogram parameters
        if nperseg <= 0 or noverlap < 0 or nfft <= 0:
            raise ValueError("nperseg, noverlap, and nfft must be positive values.")
        if noverlap >= nperseg:
            raise ValueError("noverlap must be less than nperseg.")

        # Validation of the window
        valid_windows = ['hann', 'hamming', 'blackman', 'bartlett', 'boxcar']
        if window not in valid_windows:
            raise ValueError(f"Invalid window. Choose from: {valid_windows}")

        # Configuration of attributes
        self.radar_source = radar_source
        self.sample_rate = getattr(radar_source, 'sample_rate', 1.0)
        self.output_format = getattr(radar_source, 'output_format', 'Samples')
        self.nperseg = nperseg
        self.noverlap = noverlap
        self.nfft = nfft
        self.window = window
        self.cmap = cmap
        self.waveform = None

        # Logger configuration
        self.logger = logging.getLogger(__name__)
        self.logger.setLevel(logging.INFO)

    def generate_signal(self, *args, **kwargs):
        """
        Generates the signal by calling the RadarSource/FMCWSource object.

        Parameters:
        -----------
        *args, **kwargs : extra arguments
            Arguments passed to the call() method of radar_source.

        Returns:
        --------
        waveform : tf.Tensor
            The signal generated by radar_source.
        """
        self.logger.info("Generating FMCW signal...")
        if not args and "inputs" not in kwargs:
            dummy_input = tf.constant(0)
            self.waveform = self.radar_source(dummy_input, *args, **kwargs)
        else:
            self.waveform = self.radar_source(*args, **kwargs)
        self.logger.info("FMCW signal generated successfully.")
        return self.waveform

    def _get_signal_component(self, signal, component='real'):
        """
        Extracts the specified component of the signal (real, imaginary, or magnitude).

        Parameters:
        -----------
        signal : np.ndarray
            Complex signal.
        component : str
            Component to extract ('real', 'imag', 'magnitude').

        Returns:
        --------
        np.ndarray
            The extracted signal component.
        """
        if component == 'real':
            return np.real(signal)
        elif component == 'imag':
            return np.imag(signal)
        elif component == 'magnitude':
            return np.abs(signal)
        else:
            raise ValueError("component must be 'real', 'imag', or 'magnitude'.")

    def plot_spectrogram(self, time_scale=1.0, signal_component='real', use_complex=False, scaling='spectrum',
                         figsize=(10, 6), title=None, xlabel=None, ylabel=None, save_path=None):
        """
        Plots the spectrogram of the signal.

        Parameters:
        -----------
        time_scale : float
            Time axis scaling factor (e.g., 3.0 for 3*T).
        signal_component : str
            Signal component to use ('real', 'imag', 'magnitude').
        use_complex : bool
            If True, uses the complex signal directly.
        scaling : str
            Scaling mode for the spectrogram ('spectrum' or 'density').
            Default: 'spectrum'.
        figsize : tuple
            Figure size (width, height).
        title : str
            Custom title.
        xlabel : str
            Custom label for the x-axis.
        ylabel : str
            Custom label for the y-axis.
        save_path : str
            Path to save the figure. If None, the figure is not saved.
        """
        if self.waveform is None:
            self.generate_signal()

        # Flatten the signal if it is in 'Sweeps' format
        if self.output_format.lower() == 'sweeps':
            signal_1d = tf.reshape(self.waveform, [-1])
        else:
            signal_1d = self.waveform

        # Convert to numpy
        sig_np = signal_1d.numpy()

        # Choose the signal component
        if use_complex:
            x = sig_np
        else:
            x = self._get_signal_component(sig_np, signal_component)

        # Normalize the signal
        x = x / np.max(np.abs(x))

        # Calculate the spectrogram
        f, t_spec, Sxx = spectrogram(
            x=x,
            fs=self.sample_rate,
            window=self.window,
            nperseg=self.nperseg,
            noverlap=self.noverlap,
            nfft=self.nfft,
            scaling=scaling  # 'spectrum' or 'density'
        )

        # Convert to dB
        Sxx_dB = 10 * np.log10(Sxx + 1e-12)

        # Apply time scaling
        t_spec_scaled = t_spec * time_scale

        # Plot the spectrogram
        plt.figure(figsize=figsize)
        plt.pcolormesh(t_spec_scaled / 1e6, f / 1e6, Sxx_dB, shading='gouraud', cmap=self.cmap)
        plt.title(title if title else "FMCW Signal Spectrogram")
        plt.xlabel(xlabel if xlabel else f"Time [us] (Scale: {time_scale}*T)")
        plt.ylabel(ylabel if ylabel else "Frequency [MHz]")
        cbar = plt.colorbar()
        cbar.set_label("Intensity [dB/Hz]")
        plt.tight_layout()

        # Save the figure if necessary
        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            self.logger.info(f"Spectrogram saved at: {save_path}")

        plt.show()

class TimeDomainPlotter:
    """
    Class for plotting the signal in the time domain.

    Example usage:
    ----------------
    fmcw_source = FMCWSource(...)
    plotter = TimeDomainPlotter(fmcw_source)
    plotter.generate_signal()
    plotter.plot_time_domain(signal_component='real', figsize=(10, 6), title="Signal in Time Domain")
    """

    def __init__(self, radar_source):
        """
        Initializes the TimeDomainPlotter.

        Parameters:
        -----------
        radar_source : RadarSource or FMCWSource
            Instance of a class derived from RadarSource that generates the signal.
        """
        # Validation of radar_source
        if not isinstance(radar_source, RadarSource):
            raise ValueError("radar_source must be an instance of RadarSource or a derived class.")

        # Configuration of attributes
        self.radar_source = radar_source
        self.sample_rate = getattr(radar_source, 'sample_rate', 1.0)
        self.output_format = getattr(radar_source, 'output_format', 'Samples')
        self.waveform = None

        # Logger configuration
        self.logger = logging.getLogger(__name__)
        self.logger.setLevel(logging.INFO)

    def generate_signal(self, *args, **kwargs):
        """
        Generates the signal by calling the RadarSource/FMCWSource object.

        Parameters:
        -----------
        *args, **kwargs : extra arguments
            Arguments passed to the call() method of radar_source.

        Returns:
        --------
        waveform : tf.Tensor
            The signal generated by radar_source.
        """
        self.logger.info("Generating FMCW signal...")
        if not args and "inputs" not in kwargs:
            dummy_input = tf.constant(0)
            self.waveform = self.radar_source(dummy_input, *args, **kwargs)
        else:
            self.waveform = self.radar_source(*args, **kwargs)
        self.logger.info("FMCW signal generated successfully.")
        return self.waveform

    def _get_signal_component(self, signal, component='real'):
        """
        Extracts the specified component of the signal (real, imaginary, or magnitude).

        Parameters:
        -----------
        signal : np.ndarray
            Complex signal.
        component : str
            Component to extract ('real', 'imag', 'magnitude').

        Returns:
        --------
        np.ndarray
            The extracted signal component.
        """
        if component == 'real':
            return np.real(signal)
        elif component == 'imag':
            return np.imag(signal)
        elif component == 'magnitude':
            return np.abs(signal)
        else:
            raise ValueError("component must be 'real', 'imag', or 'magnitude'.")

    def plot_time_domain(self, signal_component='real', figsize=(10, 6), title=None, xlabel=None, ylabel=None, save_path=None):
        """
        Plots the signal in the time domain.

        Parameters:
        -----------
        signal_component : str
            Signal component to use ('real', 'imag', 'magnitude').
        figsize : tuple
            Figure size (width, height).
        title : str
            Custom title.
        xlabel : str
            Custom label for the x-axis.
        ylabel : str
            Custom label for the y-axis.
        save_path : str
            Path to save the figure. If None, the figure is not saved.
        """
        if self.waveform is None:
            self.generate_signal()

        # Flatten the signal if it is in 'Sweeps' format
        if self.output_format.lower() == 'sweeps':
            signal_1d = tf.reshape(self.waveform, [-1])
        else:
            signal_1d = self.waveform

        # Convert to numpy
        sig_np = signal_1d.numpy()

        # Choose the signal component
        x = self._get_signal_component(sig_np, signal_component)

        # Create the time vector
        t = np.arange(0, len(x)) / self.sample_rate

        # Plot the signal in the time domain
        plt.figure(figsize=figsize)
        plt.plot(t * 1e6, x)  # Convert time to microseconds (us)
        plt.title(title if title else "Signal in Time Domain")
        plt.xlabel(xlabel if xlabel else "Time [us]")
        plt.ylabel(ylabel if ylabel else "Amplitude")
        plt.grid(True)
        plt.tight_layout()

        # Save the figure if necessary
        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            self.logger.info(f"Plot saved at: {save_path}")

        plt.show()